### ISSUE TITLE
Duplicate filter not working

### ISSUE THREAD

**Issue by adityadebC** [MarioVilas/googlesearch#104]
Hi, here's my code:

```
from googlesearch import search

query = 'aluminium ion battery'

my_results_list = []
for i in search(query,        # The query you want to run
                tld = 'com',  # The top level domain
                lang = 'en',  # The language
                num = 10,     # Number of results per page
                start = 0,    # First result to retrieve
                stop = None,  # Last result to retrieve
                pause = 2,  # Lapse between HTTP requests
                safe = 'high',
                extra_params={'filter':'1'}

               ):
    print(i)
```

even though I added extra_param={'filter':'1'}, it is still showing multiple urls for the same website.
According to this: https://support.google.com/gsa/answer/6329265?hl=en#
filter=1 should filter out the duplicate urls.

**Comment by MarioVilas** [comment]
Hi!

Note that this library is not using the official Google API, so I wouldn't count on that documentation to be accurate. The library uses a legacy API that's easier to scrape, and some features were intentionally removed by Google over the years too.

I recommend filtering out the duplicate results yourself in Python code, shouldn't be too difficult. For example, you can store the results in a dictionary using the domain name as the key.
