### ISSUE TITLE
No proxies ?

### ISSUE THREAD

**Issue by MrMetatron** [MarioVilas/googlesearch#105]

**Comment by opsdisk** [comment]
@MrMetatron Check out [yagooglesearch](https://github.com/opsdisk/yagooglesearch) - it's based off Mario's great work.  It supports proxies (https://github.com/opsdisk/yagooglesearch#http-and-socks5-proxy-support)

**Comment by XaviscoB** [comment]
> @MrMetatron Check out [yagooglesearch](https://github.com/opsdisk/yagooglesearch) - it's based off Mario's great work. It supports proxies (https://github.com/opsdisk/yagooglesearch#http-and-socks5-proxy-support)

Thanks :)
