### ISSUE TITLE
An outdated conda package

### ISSUE THREAD

**Issue by liutiming** [MarioVilas/googlesearch#106]
Thanks for this great package!

At first I installed via https://anaconda.org/mbonix/google, and apparently this is outdated and returns the following bs4 error with example code: 

`AttributeError: 'NoneType' object has no attribute 'findAll'`

Installing via pip has no issue :)

**Comment by ThisIsManuel** [comment]
That is a different packages. You can find googlesearch here:
https://anaconda.org/conda-forge/googlesearch

To install via conda run `conda install -c conda-forge googlesearch` instead of `conda install -c mbonix google`.
