### ISSUE TITLE
Enable use of Google's  Programmable Search?

### ISSUE THREAD

**Issue by sjscotti** [MarioVilas/googlesearch#107]
Hi
Thanks for this cool capability.  It is used in an app I just started using that does Google searches, and what I want to try next is to limit the websites that Google searches.  I found that Google has a "Programmable Search" capability (see https://programmablesearchengine.google.com/about/ ) where you provide a list of websites and it will only search these websites.  The Google call to programable search looks like this...

https://cse.google.com/cse?cx=ecda85be7e4a7a452

Can your repo be adapted to a programmable search?
Thanks!

**Comment by MarioVilas** [comment]
Hi!

This code deliberately does not use any such API from Google, since there are other, better ways of using those. This is just meant for scraping the search result pages, and I'd rather not change that - it does one thing and (hopefully!) does it well. :)

Cheers!
