### ISSUE TITLE
Searching "raytheon ticker" give first URL of a Wikipedia SVG

### ISSUE THREAD

**Issue by JohnMaguire** [MarioVilas/googlesearch#110]
First URL is https://ar.wikipedia.org/wiki/%D9%85%D9%84%D9%81:Raytheon_Technologies_logo.svg

I expected https://finance.yahoo.com/quote/RTX/ or similar.

**Comment by MarioVilas** [comment]
I don't work at Google :) no idea what to do with this ticket!

**Comment by JohnMaguire** [comment]
@MarioVilas One of us must be misunderstanding... this is not the first URL in a search for "raytheon ticker." I think the scraper isincorrectly pulling the logo from the ticker graph at the top of the page, rather than the URL for the first search result.

Or I misunderstand the goal of the search function.

**Comment by JohnMaguire** [comment]
Screenshots for further clarification... the logo in this first image is returned for a call to `search("raytheon ticker")`:

![logo](https://user-images.githubusercontent.com/440033/155608723-3b5ea115-9467-4e64-ad6f-adc4fc8cdd20.png)

I expected the purple link to be the first result:

![results](https://user-images.githubusercontent.com/440033/155608732-c108f5e7-93e0-48eb-9b97-03d79642b24e.png)

**Comment by JohnMaguire** [comment]
@MarioVilas No rush on this, just wanted to make sure you saw the above comment.

**Comment by JohnMaguire** [comment]
@MarioVilas Ping on this again... I believe this is a valid ticket. We can do more to parse the results and get the first link in the results.

The bug isn't that Google is returning the SVG, the bug is that we're not correctly ignoring it, IMO.
