### ISSUE TITLE
Installation instructions bring some other library

### ISSUE THREAD

**Issue by scoricov** [MarioVilas/googlesearch#114]
When using command from the README to install this module 'pip install google', a module will be installed, but its code will be of some other repository. Likely this is `https://github.com/anthonyhseb/googlesearch`

As a result, other instructions in the docs won't work as well.

Alternatively, this worked for me:
```
pip3 install -e git+https://github.com/MarioVilas/googlesearch#egg=google
```

**Comment by MarioVilas** [comment]
That is very odd, because the package in PyPi is definitely mine: https://pypi.org/project/google/

**Comment by MarioVilas** [comment]
Issue is very old and could not reproduce, closing now.
