### ISSUE TITLE
Searching Google Based Websites

### ISSUE THREAD

**Issue by telboon** [MarioVilas/googlesearch#35]
**Issue:**
Script is not able to search for or find google-based websites as results

**Reproducible Use:**
x=google.search("site:google.com apple")

**Expected Result:**
"feedproxy.google.com/~r/zdnet/Apple/~3/5eQ2k0HRMgc/"

**Actual Result:**
No site found (in fact a ban from Google for 3-6 hours)

**Comment by telboon** [comment]
I read the source and found that it's due to filter_result() function. 

Is it possible to parse using <h3> and finding the <a> within <h3> tags? This will allow more careful picking of the search results, reducing the need to filter anything that has "google" in the url

**Comment by MarioVilas** [comment]
That would definitely be better. Bear in mind this was born out of a 10-minute script I needed for something specific so I never even considered that use case :D

**Comment by MelissaMV** [comment]
Hey @MarioVilas  can you provide some usage examples thx much :)
