### ISSUE TITLE
Less Hits than expected

### ISSUE THREAD

**Issue by agneet42** [MarioVilas/googlesearch#37]
I am doing this :

`for url in search("Microsoft", stop = 500):`

It gives me 137 links instead of 500. Any hints as to why?

**Comment by brandomr** [comment]
@agneet42 you're IP is probably getting flagged by Google

**Comment by agneet42** [comment]
@brandomr, thanks for the quick reply. 
Is there a way around to avoid being flagged?

**Comment by brandomr** [comment]
@agneet42 first I'd confirm that's happening by trying to re-run the query or other queries. If you receive low or no results then that is probably indeed the issue. 

If you are running this locally on your computer without a VPN you could try going to google.com and running a search in browser and seeing if you are thrown a captcha.

Are you getting any error or anything like that?
