### ISSUE TITLE
Cannot import Search  

### ISSUE THREAD

**Issue by abdelmalek13** [MarioVilas/googlesearch#63]
I 've read this #39 issue but it does me no good 
I'm using python 3.5 
When I type 

`>>>from googlesearch import search`
this is what I got 
`ImportError: cannot import name 'search'`

everything else is fine I can import the library without `search` 

`>>> dir(googlesearch)' 

`['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__','__spec__', '__version__']`

`>>> googlesearch
<module 'googlesearch' from 'C:\\Users\\abdelmalek\\AppData\\Local\\Programs\\Python\\Python35\\lib\\site-packages\\googlesearch\\__init__.py'>`

**Comment by MarioVilas** [comment]
Cannot reproduce:
```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from googlesearch import search
>>> search
<function search at 0x7f83174f0bf8>
>>> import googlesearch
>>> dir(googlesearch)
['BeautifulSoup', 'LWPCookieJar', 'Request', 'USER_AGENT', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'cookie_jar', 'filter_result', 'get_page', 'get_random_user_agent', 'hits', 'home_folder', 'install_folder', 'is_bs4', 'lucky', 'math', 'ngd', 'os', 'parse_qs', 'quote_plus', 'random', 'search', 'search_apps', 'search_books', 'search_images', 'search_news', 'search_shop', 'search_videos', 'sys', 'time', 'url_home', 'url_next_page', 'url_next_page_num', 'url_search', 'url_search_num', 'urlopen', 'urlparse', 'user_agents_file', 'user_agents_list']
>>> 
```
Looks to me like you've got something else installed there...

**Comment by abdelmalek13** [comment]
I'm really sorry 
I mistook your library for googlesearch 
It's my bad
now it works fine

**Comment by MarioVilas** [comment]
No problem :)
