### ISSUE TITLE
Missing Catch for Google's 503

### ISSUE THREAD

**Issue by luannaufal** [MarioVilas/googlesearch#66]
I feel it misses a parameters asking the user for a function to be run in case it identifies that Google threw a *503* result. 
So in this case, an user could implement a function to receive the html and deal with the ReCaptcha and to continue the fast pace of crawling. 
When this situation happens, Google throws this redirect: https://www.google.com/sorry/index
I add the HTML from this page, in order to be used as base for coding, or even can help with adding this improvement, just let me know what you prefer.
<img width="1616" alt="screen shot 2019-01-08 at 13 22 27" src="https://user-images.githubusercontent.com/8204335/50840077-ddb96a80-1348-11e9-8b9e-2964840384c4.png">
[Error Page.zip](https://github.com/MarioVilas/googlesearch/files/2737327/Error.Page.zip)

**Comment by hm43** [comment]
I'm facing same error, when I want to search for a big list of words.

**Comment by MarioVilas** [comment]
If I'm not mistaken, urllib2 already raises HTTPError exceptions, so you can just catch that and check for the error code: https://docs.python.org/3/library/urllib.error.html#urllib.error.HTTPError
