### ISSUE TITLE
Fetch next n urls

### ISSUE THREAD

**Issue by gauravccsu** [MarioVilas/googlesearch#69]
Hi,

I request to find a solution to fetch next n URLS.
What i am trying to do is after fetching the URLS, I fetch the contents from websource, but if the result is not appropriate, again fetch new URLs for the same search string.
For example, first i fetched 10 URLs and i need next 5 URLs. Please help me out

**Comment by MarioVilas** [comment]
Hi, the start and stop arguments can help you do this. Hope that helps! :)
