### ISSUE TITLE
Unable to see filtered results

### ISSUE THREAD

**Issue by gitmunks** [MarioVilas/googlesearch#74]
Google tacks on "&filter=0" to represent choosing the option to not omit items. I'm wanting to add this functionality but not sure where to start. Fairly new to using git in general, is it possible to make my own branch with this feature?--thanks!

**Comment by MarioVilas** [comment]
Hi! Can you give me a bit more detail on what that URL argument does? In any case you can pass it with the extra_params argument so in principle no changes are needed, but if it's an interesting option I may add it by default.
