### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by ran88dom99** [MarioVilas/googlesearch#75]
```
try: 
    from googlesearch import search 
except ImportError:  
    print("No module named 'google' found") 
  
xx = []
query = ["zenobase" , "exist.io" , "gyrosco.pe" , "quantimodo"]  
print(query)
#requests.get(link, headers = {'User-agent': 'mymerge bot 0.1'}) need python requests package, user_agent="rua"
# to search 
for q in query:
    for j in search(q, tld="com", num=10, stop=2, pause=20): 
        xx.append(j)
        print(xx)
```
Ran fine before modifications. Maybe caused by me setting num=3000 and pause=2 previously.
Using user_agent="rua" did not help. Browsers still use google fine.

**Comment by ran88dom99** [comment]
Everything works after not doing anything for a few hours. I guess the server just did not like my 3k length page and suspended me.

**Comment by Aens** [comment]
Hm, the same piece of code works on my computer but it fails to work on my VPN. Any guesses?

**Comment by MarioVilas** [comment]
Perhaps the VPN IP address has been blacklisted by Google. The same thing happens with Tor exit nodes by the way.
