### ISSUE TITLE
How to get title and snippet from result?

### ISSUE THREAD

**Issue by kodfactory** [MarioVilas/googlesearch#82]
Hi,

First of all thank you for making such wonderful and easy to use library. 

I am able to make it work, But now i want to get the title and snippet for better performance and to use it further.

Can i do it using this?

Below is simple code which is giving me the urls only.

```
from googlesearch import search

for url in search('best usb powered monitor', tld='com', stop=10):
    print(url)
```

And what things i need to consider if i am going to use this library for enterprise application?

Thanks,
Jayesh (Kod Factory)

**Comment by MarioVilas** [comment]
I'm afraid the library only retrieves the links, not the titles.
