### ISSUE TITLE
ngd function is not working.

### ISSUE THREAD

**Issue by GrilledChickenThighs** [MarioVilas/googlesearch#83]
Trying to call the ngd function with some basic terms
```    
    term1 = 'macbeth'
    term2 = 'shakespeare'
    relationship = ngd(term1, term2)
    print(relationship)
```
And I'm getting this error. I've tried a couple other terms, but this ngd should definitely come up with some results...

```Traceback (most recent call last):
  File "remake.py", line 132, in <module>
    relationship = ngd(term1, term2)
  File "/lib/python3.7/site-packages/googlesearch/__init__.py", line 766, in ngd
    lhits1 = math.log10(hits(term1))
  File "/lib/python3.7/site-packages/googlesearch/__init__.py", line 745, in hits
    tag = soup.find_all(attrs={"class": "sd", "id": "resultStats"})[0]
IndexError: list index out of range
```

**Comment by MarioVilas** [comment]
Looks like Google changed something in their HTML output. I did not write that function (came from a pull request) but I'll try my best to fix it.

**Comment by MarioVilas** [comment]
Ugh, the number of hits was completely removed from the legacy web page. I don't think this functionality can be implemented again :(

**Comment by MarioVilas** [comment]
I removed the non working code for now in e48e540b421367e6fb5efeab147c8a2723675a2b, leaving this ticket open in case anyone comes up with a good idea on how to bring back this feature...

**Comment by GrilledChickenThighs** [comment]
Thanks for the good work @MarioVilas. Much appreciated. I just downloaded your module yesterday and was exploring the various functions. I thought this one was interesting, but it's unnecessary for my needs so don't lose any sleep over this.

**Comment by MarioVilas** [comment]
You're welcome!

Closing this issue until I figure out a way to bring the feature back.
