### ISSUE TITLE
HTTPError: Too Many Requests

### ISSUE THREAD

**Issue by Fulvioo** [MarioVilas/googlesearch#85]
Running the sample code 

`from googlesearch import search`
`for url in search('"Breaking Code" WordPress blog', stop=20):`
`print(url)`

I always obtain this error

`File \urllib\request.py line 650 in http_error_default`
`raise HTTPError(req.full_url, code, msg, hdrs, fp)`
`HTTPError: Too Many Requests`

**Comment by MarioVilas** [comment]
Immediately or after a long while? Google will start asking for a CAPTCHA or straight up temporarily blocking your IP if you make too many searches too quickly. For some IP addresses that happens immediately (for example if you use Tor).

**Comment by Fulvioo** [comment]
It was quite immediate and I dont use tor.
Anyway I've then restarted the internet connection in order to obtain a differen IP, and now it works.
I think I shall capture this error and create an exception in order to handle it with a timeout or other workarounds. 
You can close the issue or mark as enhancement, as you prefer

**Comment by MarioVilas** [comment]
There was already an enhancement to do this so I'll close the issue now. Thanks! :)

**Comment by Fulvioo** [comment]
Hello Mario, FYI 
I have tried 3 ways to handle the HTTPerror:
- changing the domine .com to `random.choiche(['com','co.uk','it'])`
- reimporting your module `importlib.reload(googlesearch)`
- waiting 5mins `time.sleep(310)`
but all this appears to be not influent on the error

**Comment by orcjun** [comment]
I tried deleting $home folder's `.google-cookie` file, and it works!
