### ISSUE TITLE
ModuleNotFoundError: No module named 'googlesearch'

### ISSUE THREAD

**Issue by Talha089** [MarioVilas/googlesearch#86]
I have installed google by
$ pip install google
$ pip3 install google
and when im trying to import the google search it throws an error:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-959aaf889b0e> in <module>
      5 from scrapy.crawler import CrawlerProcess
      6 from scrapy.linkextractors.lxmlhtml import LxmlLinkExtractor
----> 7 from googlesearch import search

ModuleNotFoundError: No module named 'googlesearch'

**Comment by MarioVilas** [comment]
Beats me. Sounds like something wrong with your Python install?

**Comment by Talha089** [comment]
yes maybe, 
Can you sort this out?
Where Am i having trouble? Other libraries are working fine like scrapy pandas etc.
I'm running python2+ as a default and using python 3+ in anaconda.
