### ISSUE TITLE
 search limit

### ISSUE THREAD

**Issue by juanfranciscomunoz** [MarioVilas/googlesearch#88]
What is the search limit before Google blocks you?

**Comment by MarioVilas** [comment]
No idea, it seems to depend on many factors. I use trial and error.

**Comment by knassar702** [comment]
##### Hi @juanfranciscomunoz , 
##### You Can Use Proxy for bypass it , i use <a href='https://github.com/haad/proxychains'>proxychains</a> for this issues

**Comment by freshforlife** [comment]
> ##### Hi @juanfranciscomunoz ,
> ##### You Can Use Proxy for bypass it , i use [proxychains](https://github.com/haad/proxychains) for this issues


@knassar702 , Can you post a snippet of code how the proxychains work with this googlesearch package.
