### ISSUE TITLE
Detect type result search.

### ISSUE THREAD

**Issue by trung-hiro** [MarioVilas/googlesearch#89]
Hi , i read your code , and i see you have some type (ex : images, videos, news, shopping, books, apps). So i your result , why you didn't return result ulr + type of this url display in google when param tpe='' be set default.!

**Comment by MarioVilas** [comment]
Thing is, if you're calling any of those functions or using the tpe parameter, then you already know what type of results you're getting. So the code would be giving you something you already have, which is redundant.
