### ISSUE TITLE
Getting the website title?

### ISSUE THREAD

**Issue by Sahaj-15** [MarioVilas/googlesearch#91]
Alright, I am searching Google using what is displayed in the documentation, but how can we get the title of the Search results?

I don't think there is a way to really do this, maybe add this?

**Comment by Sahaj-15** [comment]
This is basically it:
`from googlesearch import search
for url in search('"Breaking Code" WordPress blog', stop=20):
    print(url)`

**Comment by MarioVilas** [comment]
Sorry, it's "safer" to just get the URLs. I want to limit scraping to the bare minimum logic so I don't have to run after Google every time they change something...
