### ISSUE TITLE
Search more than 1 query at same time

### ISSUE THREAD

**Issue by alonsillou** [MarioVilas/googlesearch#93]
Hi,

First, thanks for this "masterpiece".

Second, my issue is than i need search more than just 1 query at same time, how can i do it?

I try with a list, but the console show me a Traceback.

I read the doc, but i can't find the information.

(In query, im using variable "q" and q is my query, if i put just one string is ok, but with a list doesn't work)

PD: Im rookie, sorry if is a stupid question.

Thanks.

**Comment by MarioVilas** [comment]
Hi! Thanks for your kind words :)

To include more than one search term just separate them with spaces, like this: q="word another_word one_more_word"
