### ISSUE TITLE
How to use cookie_jar for block  cookie?please provide any example for using cookie_jar in code

### ISSUE THREAD

**Issue by pritam-raj** [MarioVilas/googlesearch#97]
Thanks

**Comment by MarioVilas** [comment]
If you want to block the Google cookie, I wouldn't recommend it, in my experience that just makes Google block you faster. Some users reported that deleting the cookie *after* you've been blocked by Google does help however. Just deleting the file works, but if you want to do it from code, here are the docs:

Python 2.x: https://docs.python.org/2/library/cookielib.html

Python 3.x: https://docs.python.org/3/library/http.cookiejar.html#module-http.cookiejar

Let me know if that helps, or you have any other questions! :)

**Comment by pritam-raj** [comment]
Thanks..
