### ISSUE TITLE
cannot import name 'search' from googlesearch

### ISSUE THREAD

**Issue by Ash4059** [MarioVilas/googlesearch#99]
what is the package name for the installation of the module and version also? I'm getting error during the deployment of a model.
https://phishingurldetection.herokuapp.com/ this is the link where you can checkout for error
and I have written from googlesearch import search but still I'm getting error that cannot import name 'search'
I have included these module in requirements. txt->
google==3.0.0
google-api-core==1.22.2
google-api-python-client==1.11.0
google-auth==1.21.1
google-auth-httplib2==0.0.4
google-search==1.0.2
googleapis-common-protos==1.52.0
but still I'm getting error that cannot import name 'search'

**Comment by MarioVilas** [comment]
The package name is "googlesearch" (no hyphen) and it looks like you haven't installed it. What you have are the official Google APIs, this is an unofficial project that predates those.

**Comment by Ash4059** [comment]
C:\Users\jaisw>pip install googlesearch
ERROR: Could not find a version that satisfies the requirement googlesearch (from versions: none)
ERROR: No matching distribution found for googlesearch

**Comment by Ash4059** [comment]
And for google, I have checked the directory but they don't have  search
 dir(google)
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'logging']

**Comment by MarioVilas** [comment]
The pypi name does not match the actual module name. Sadly I had to change it because Google complained.

**Comment by MarioVilas** [comment]
This is the module on pypi: https://pypi.org/project/google/#history

**Comment by Ash4059** [comment]
Thank you so much for reply

**Comment by MarioVilas** [comment]
No prob! Sorry for the confusion :( wish I had been able to keep my original module name...
